%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\Inês\Documents\MATLAB\lnec_temp_data.csv
%
% Auto-generated by MATLAB on 28-Sep-2021 14:45:34

%% Setup the Import Options
% opts = delimitedTextImportOptions("NumVariables", 3);

% Specify range and delimiter
% opts.DataLines = [2, Inf];
% opts.Delimiter = ",";

% Specify column names and types
% opts.VariableNames = ["x", "y", "Var3"];
% opts.SelectedVariableNames = ["x", "y"];
% opts.VariableTypes = ["datetime", "double", "string"];
% opts = setvaropts(opts, 1, "InputFormat", "yy-MM-dd HH:mm");
% opts = setvaropts(opts, 3, "WhitespaceRule", "preserve");
% opts = setvaropts(opts, 3, "EmptyFieldRule", "auto");
% opts.ExtraColumnsRule = "ignore";
% opts.EmptyLineRule = "read";

% Import the data
format long
lnectempdata = readtable("C:\Users\Inês\Dropbox\Mestrado\Tese\Reports\Data Quality\Tese João Penim\ANNODE-Framework-master\scripts\lnec_temp_data_2020_2021.csv");
p=posixtime(datetime(lnectempdata{:,2}, "InputFormat", "dd-MM-yy HH:mm"));
q=lnectempdata{:,1};
data = [reshape(p.', [], 1), reshape(q.', [], 1)];
save('C:\Users\Inês\Dropbox\Mestrado\Tese\Reports\Data Quality\Tese João Penim\ANNODE-Framework-master\scripts\lnec_temp_data_2020_2021_not_raw.mat','data')

%% Clear temporary variables
clear opts